name: Android CI

on:
  push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build APK using Gradle Wrapper
              run: ./gradlew assembleRelease

            - name: Upload release APK
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: android/app/build/outputs/apk/release/*.apk # Verify this path
