name: Android CI

on:
  push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build with Gradle Action
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 8.2.1 # Or your version
                  arguments: assembleRelease
                  gradle-user-home: ~/.gradle # Explicitly set Gradle user home
                  build-file: ./android/build.gradle # Explicitly point to the build file
                  wrapper-directory: ./android/gradle/wrapper # Explicitly point to the wrapper directory

            - name: Upload release APK
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: android/app/build/outputs/apk/release/*.apk # Adjust if needed
